# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres_123
ENV POSTGRES_DB=calendar_db

# Expose PostgreSQL default port
EXPOSE 5432
